# Generated by Django 3.2 on 2021-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='EGP', help_text='User default currency.', max_length=5),
        ),
    ]
