# Generated by Django 3.2 on 2021-04-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchase_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='owner',
            new_name='purchaser',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price_currency',
        ),
    ]
