# Generated by Django 3.2 on 2021-04-25 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_auto_20210424_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 25, 20, 12, 3, 475218, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
